using DataAccessMsSqlServerProvider.com.vapstech.IssueManager;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace CommonLibrary
{
    public class PettyCash_AutoRefernceNo_Generation
    {
        public PettyCashContext _db;

        public PettyCash_AutoRefernceNo_Generation(PettyCashContext db)
        {
            _db = db;
        }

        public string GenerateReferenceNo(long MI_Id, long IMFY_Id, string GenTypeFlag)
        {
            string AutoGeneratedNo = "";
            try
            {
                using (var cmd = _db.Database.GetDbConnection().CreateCommand())
                {
                    cmd.CommandText = "PC_AutoGeneration_ReferenceNo";
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.Add(new SqlParameter("@MI_Id", SqlDbType.VarChar) { Value = MI_Id });
                    cmd.Parameters.Add(new SqlParameter("@IMFY_Id", SqlDbType.VarChar) { Value = IMFY_Id });
                    cmd.Parameters.Add(new SqlParameter("@GenTypeFlag", SqlDbType.VarChar) { Value = GenTypeFlag });
                    cmd.Parameters.Add(new SqlParameter("@AutogenerateNo", SqlDbType.VarChar, Int32.MaxValue) { Direction = ParameterDirection.Output });

                    if (cmd.Connection.State != ConnectionState.Open)
                        cmd.Connection.Open();

                    var data1 = cmd.ExecuteNonQuery();

                    AutoGeneratedNo = cmd.Parameters["@AutogenerateNo"].Value.ToString();
                }
            }
            catch (Exception ex)
            {
                AutoGeneratedNo = "Error";
                Console.WriteLine(ex.Message);
            }

            return AutoGeneratedNo;
        }
    }
}
