using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PreadmissionDTOs.com.vaps.Exam
{
    public class VikasaSubjectwiseCumulativeReportDTO
    {
        public long MI_Id { get; set; }
        public long HRME_Id { get; set; }
        public long ASMAY_Id { get; set; }
        public long ASMCL_Id { get; set; }
        public long ASMS_Id { get; set; }
        public long EME_Id { get; set; }
        public long EME_Id_New { get; set; }
        public long ISMS_Id { get; set; }
        public string yearname { get; set; }
        public string ClassName { get; set; }
        public string SubjectName { get; set; }
        public string sectionname { get; set; }
        public string radiotype { get; set; }
        public Array subjectList { get; set; }
        public Array subjlistfalse { get; set; }
        public Array BasicListYear { get; set; }
        public Array BasiListclass { get; set; }
        public Array gradeList { get; set; }
        public Array BasiListsectiont { get; set; }
        public Array BasiListcategory { get; set; }
        public Array BasiListsubject { get; set; }
        public Array sectionList { get; set; }
        public Array classlist { get; set; }
        public Array yearlist { get; set; }
        public Array termlist { get; set; }
        public Array clstchname { get; set; }
        public Array savelisttot { get; set; }
        public Array subjlist { get; set; }
        public Array grade_details { get; set; }
        public Array empAttendence { get; set; }
        public int EYCES_SubjectOrder { get; set; }
        public Array studentList { get; set; }
        public Array ExamList { get; set; }
        public Array categoryList { get; set; }
        public long EMCA_Id { get; set; }
       public decimal classheld { get; set; }
        public decimal classatt { get; set; }
        public int EYC_Id { get; set; }
        public Array ExamGroupname { get; set; }
        public string EMPSG_GroupName { get; set; }
        public decimal? EMPSG_PercentValue { get; set; }
        public decimal? EMPSG_MarksValue { get; set; }
        public int EMPSG_Id { get; set; }
        public Array examgroupmarks { get; set; }
        public Array studentlist { get; set; }
        public long AMST_Id { get; set; }
        public decimal? ESTMPS_MaxMarks { get; set; }
        public decimal? ESTMPS_ObtainedMarks { get; set; }
        public string ESTMPS_ObtainedGrade { get; set; }
        public decimal? TotalObtMarks { get; set; }
        public decimal? ESTMPS_ClassAverage { get; set; }      
        public Array gradelist { get; set; }
        public Array classteacher { get; set; }
        public string empname { get; set; }
        public Array instname { get; set; }
        public List<VikasaSubjectwiseCumulativeReportDTO> savelist { get; set; }
        public long AMAY_RollNo { get; set; }
        public bool EYCES_AplResultFlg { get; set; }
        public decimal? EYCES_MaxMarks { get; set; }
        public decimal? EYCES_MinMarks { get; set; }
        public string graderemark { get; set; }
        public string ESTMP_TotalGradeRemark { get; set; }
        public int EMGR_Id { get; set; }
        public string MI_name { get; set; }
        public string EME_ExamName { get; set; }
        public string EME_ExamCode { get; set; }
        public int EME_ExamOrder { get; set; }
        public bool EME_FinalExamFlag { get; set; }
        public bool EME_ActiveFlag { get; set; }
        public Array exammastername { get; set; }
        public string returnduplicatestatus { get; set; }
        public bool returnval { get; set; }
        public Array editlist { get; set; }
        public Array amstlist { get; set; }
        public string retrunMsg { get; set; }
        public exammasterDTO[] examDTO { get; set; }       
        public string AMST_LastName { get; set; }
        public string AMST_AdmNo { get; set; }
        public DateTime? AMST_DOB { get; set; }
        public int ELP_Id { get; set; }
        public long Login_Id { get; set; }
        public string ELP_Flg { get; set; }
        public bool ELP_ActiveFlg { get; set; }
        public int ELPS_Id { get; set; }
        public bool ELPs_ActiveFlg { get; set; }
        public int ELPSS_Id { get; set; }
        public int EMSS_Id { get; set; }
        public long User_Id { get; set; }
        public string UserName { get; set; }
        public Array ctlist { get; set; }
        public Array grouplist { get; set; }       
        public Array seclist { get; set; }       
        public Array subsubject { get; set; }
        public Array studlist { get; set; }
        public Array studmaplist { get; set; }
        public Array gtdetailsview { get; set; }
        public Array edclasslist { get; set; }
        public Array emplist { get; set; }
        public Array userlist { get; set; }
        public Array pllist { get; set; }
        public Array clastechlt { get; set; }
        public Array editlist1 { get; set; }       
        public Array savelisttemp { get; set; }
        public Array nonsubjlist { get; set; }
        public List<VikasaSubjectwiseCumulativeReportDTO> savenonsubjlist { get; set; }
        public tempPrivilagesDTO[] selectedclass { get; set; }
        public Array tempdata { get; set; }
        public int EMG_Id { get; set; }
        public string EMG_GroupName { get; set; }       
        public string EMCA_CategoryName { get; set; }
        public int ECAC_Id { get; set; }
        public string ASMCL_ClassName { get; set; }
        public string ISMS_SubjectName { get; set; }
        public string ISMS_SubjectCode { get; set; }
        public string AMST_FirstName { get; set; }
        public string AMST_MiddleName { get; set; }
        public string ASMC_SectionName { get; set; }
        public string ASMAY_Year { get; set; }
        public string EMSS_SubSubjectName { get; set; }      
        public string HRME_EmployeeFirstName { get; set; }
        public long IVRMULF_Id { get; set; }
        public long Emp_Code { get; set; }
        public int ESTMPS_Id { get; set; }
        public decimal? ESTMPS_SectionAverage { get; set; }
        public decimal? ESTMPS_ClassHighest { get; set; }
        public decimal? ESTMPS_SectionHighest { get; set; }
        public string ESTMPS_PassFailFlg { get; set; }
        public int ESTMP_Id { get; set; }
        public decimal? ESTMP_TotalMaxMarks { get; set; }
        public decimal? ESTMP_TotalObtMarks { get; set; }
        public decimal? ESTMP_Percentage { get; set; }
        public string ESTMP_TotalGrade { get; set; }
        public int? ESTMP_ClassRank { get; set; }
        public int? ESTMP_SectionRank { get; set; }
        public string ESTMP_Result { get; set; }
        public Array exmstdlist { get; set; }
        public long ISMS_Order { get; set; }
        public Array examsubjectwise_details { get; set; }
        public Array sectionaverage { get; set; }
        public Array getreport { get; set; }
        public Array getreporthead { get; set; }
        public string Type { get; set; }
        public Array Work_attendence { get; set; }
        public Array Present_attendence { get; set; }        
        public Array remarks { get; set; }
        public long ECT_Id { get; set; }
        public Array subject_group { get; set; }
        public string internalgrade { get; set; }
        public Array cbsesavelist { get; set; }
        public Array cbsesubexamlist { get; set; }
        public Array cbsestudentlist { get; set; }
        public Array cbsesubjectlist { get; set; }
        public Array getgradenames { get; set; }
        public Array getstudentdetails { get; set; }
        public Array getsubjectlist { get; set; }
        public Array getexamlist { get; set; }
        public Array getsavedlist { get; set; }
        public Array getsubjectavg { get; set; }
        public decimal? ESTMPPS_SectionAverage { get; set; }
        public student_temp[] student_temp { get; set; }
    }

    public class student_temp
    {
        public long AMST_Id { get; set; }
    }
}
