using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace PreadmissionDTOs.com.vaps.admission
{
  public  class studenttccustomreportDTO
    {
       public string report_type { get; set; }
        public Array accyear { get; set; }
        public Array accclass { get; set; }
        public Array accsection { get; set; }
        public Array academicList { get; set; }
        public Array MasterCompany { get; set; }
        public Array fillsec { get; set; }
        public Array fillstud { get; set; }
        public Array fillclass { get; set; }
        public string regornamedetails { get; set; }
        public Array studentlist { get; set; }
        public long ASMC_Id { get; set; }
        public Array studentList { get; set; }
        public string classjoinname { get; set; }
        public string streamname { get; set; }
        public long? joinclassid { get; set; }
        public Array classnamejoin { get; set; }
        public Array previousschool { get; set; }
        public long? classid { get; set; }
        public Array getnextclass { get; set; }
        public Array academicList1 { get; set; }
        public string companyname { get; set; }
        public string name { get; set; }
        public Array studentTCList { get; set; }
        public string Nationality { get; set; }
        public DateTime ASTC_LastAttendedDate { get; set; }
        public string astC_TCNO { get; set; }
        public string astC_LeavingReason { get; set; }
        public string Last_Class_Studied { get; set; }
        public string ASTC_Remarks { get; set; }
        public string Religion { get; set; }
        public String caste { get; set; }
        public string ASTC_Qual_PromotionFlag { get; set; }
        public decimal? Fee_Due_Amnt { get; set; }
        public decimal? Library_Due_Amnt { get; set; }
        public decimal? Store_Canteen_Due { get; set; }
        public decimal? PDA_Due { get; set; }
        public DateTime astC_TCIssueDate { get; set; }
        public string ASTC_Conduct { get; set; }
        public string logo { get; set; }
        public string classname { get; set; }
        public string qualificlass { get; set; }
        public DateTime tcdatess { get; set; }
        public string studentname { get; set; }
        public string tctemporper { get; set; }
        public string langustudies { get; set; }
        public string electivestudies { get; set; }
        public string promotedflag { get; set; }
        public string feedue { get; set; }
        public string feeconcession { get; set; }
        public long totalworkingdays { get; set; }
        public long noworkingdays { get; set; }
        public string govtadmno { get; set; }
        public DateTime ASTC_TCApplicationDate { get; set; }
        public string subcaste { get; set; }
        public string medium { get; set; }
        public Array studenttcdetails { get; set; }
       //========section
        public long ASMS_Id { get; set; }
        public long MI_Id { get; set; }
        public string ASMC_SectionName { get; set; }
        public string ASMC_SectionCode { get; set; }
        public int ASMC_Order { get; set; }
        public int ASMC_ActiveFlag { get; set; }
        public int ASMC_MaxCapacity { get; set; }
        //=============class
        public long ASMCL_Id { get; set; }
        public string ASMCL_ClassName { get; set; }
        public int ASMCL_MinAgeYear { get; set; }
        public int ASMCL_MinAgeMonth { get; set; }
        public int ASMCL_MinAgeDays { get; set; }
        public int ASMCL_MaxAgeYear { get; set; }
        public int ASMCL_MaxAgeMonth { get; set; }
        public int ASMCL_MaxAgeDays { get; set; }
        public int ASMCL_Order { get; set; }
        public string ASMCL_ClassCode { get; set; }
        public bool ASMCL_ActiveFlag { get; set; }
        public int ASMCL_MaxCapacity { get; set; }
        public int ASMCL_PreadmFlag { get; set; }
       //==============year
        public long ASMAY_Id { get; set; }
        [ForeignKey("MI_Id")]
        public string ASMAY_Year { get; set; }
        public DateTime? ASMAY_From_Date { get; set; }
        public DateTime? ASMAY_To_Date { get; set; }
        public DateTime? ASMAY_PreAdm_F_Date { get; set; }
        public DateTime? ASMAY_PreAdm_T_Date { get; set; }
        public int ASMAY_Order { get; set; }
        public int ASMAY_ActiveFlag { get; set; }
        public DateTime? ASMAY_Cut_Of_Date { get; set; }
        public int ASMAY_Pre_ActiveFlag { get; set; }
        public bool Is_Active { get; set; }
        public bool ASMAY_ReggularFlg { get; set; }
        public bool ASMAY_NewFlg { get; set; }
        public bool ASMAY_NewAdmissionFlg { get; set; }
        public DateTime? ASMAY_TransportSDate { get; set; }
        public DateTime? ASMAY_TransportEDate { get; set; }
        public long ASMAY_CreatedBy { get; set; }
        public long ASMAY_UpdatedBy { get; set; }
        public DateTime? ASMAY_ReferenceDate { get; set; }
        public string ASMAY_AcademicYearCode { get; set; }
        public DateTime? ASMAY_AdvanceFeeDate { get; set; }
        public DateTime? ASMAY_RegularFeeFDate { get; set; }
        public DateTime? ASMAY_RegularFeeTDate { get; set; }
        public DateTime? ASMAY_ArrearFeeDate { get; set; }
      //==========student
        public long AMST_Id { get; set; }
        public string AMST_FirstName { get; set; }
        public string AMST_MiddleName { get; set; }
        public string AMST_LastName { get; set; }
        public DateTime AMST_Date { get; set; }
        public string AMST_RegistrationNo { get; set; }
        public string AMST_AdmNo { get; set; }
        public long? AMC_Id { get; set; }
        public string AMST_Sex { get; set; }
        public DateTime AMST_DOB { get; set; }
        public string AMST_DOB_Words { get; set; }
        public int? PASR_Age { get; set; }
        public string AMST_BloodGroup { get; set; }
        public string AMST_MotherTongue { get; set; }
        public string AMST_BirthCertNO { get; set; }
        public long? IVRMMR_Id { get; set; }
        public long? IMCC_Id { get; set; }
        public long? IC_Id { get; set; }
        public string AMST_PerStreet { get; set; }
        public string AMST_PerArea { get; set; }
        public string AMST_PerCity { get; set; }
        public string AMST_PerAdd3 { get; set; }
        public long? AMST_PerState { get; set; }
        public long? AMST_PerCountry { get; set; }
        public int? AMST_PerPincode { get; set; }
        public string AMST_ConStreet { get; set; }
        public string AMST_ConArea { get; set; }
        public string AMST_ConCity { get; set; }
        public long? AMST_ConState { get; set; }
        public long? AMST_ConCountry { get; set; }
        public int? AMST_ConPincode { get; set; }
        public long? AMST_AadharNo { get; set; }
        public string AMST_StuBankAccNo { get; set; }
        public string AMST_StuBankIFSC_Code { get; set; }
        public string AMST_StuCasteCertiNo { get; set; }
        public long AMST_MobileNo { get; set; }
        public string AMST_emailId { get; set; }
        public string AMST_FatherAliveFlag { get; set; }
        public string AMST_FatherName { get; set; }
        public long? AMST_FatherAadharNo { get; set; }
        public string AMST_FatherSurname { get; set; }
        public string AMST_FatherEducation { get; set; }
        public string AMST_FatherOccupation { get; set; }
        public string AMST_FatherOfficeAdd { get; set; }
        public string AMST_FatherDesignation { get; set; }
        public decimal? AMST_FatherMonIncome { get; set; }
        public decimal? AMST_FatherAnnIncome { get; set; }
        public long? AMST_FatherNationality { get; set; }
        public long? AMST_FatherMobleNo { get; set; }
        public string AMST_FatheremailId { get; set; }
        public string AMST_FatherBankAccNo { get; set; }
        public string AMST_FatherBankIFSC_Code { get; set; }
        public string AMST_FatherCasteCertiNo { get; set; }
        public string ANST_FatherPhoto { get; set; }
        public string AMST_MotherAliveFlag { get; set; }
        public string AMST_MotherName { get; set; }
        public long? AMST_MotherAadharNo { get; set; }
        public string AMST_MotherSurname { get; set; }
        public string AMST_MotherEducation { get; set; }
        public string AMST_MotherOfficeAdd { get; set; }
        public string AMST_MotherOccupation { get; set; }
        public string AMST_MotherDesignation { get; set; }
        public decimal? AMST_MotherMonIncome { get; set; }
        public decimal? AMST_MotherAnnIncome { get; set; }
        public long? AMST_MotherNationality { get; set; }
        public long? AMST_MotherMobileNo { get; set; }
        public string AMST_MotherEmailId { get; set; }
        public string AMST_MotherBankAccNo { get; set; }
        public string AMST_MotherBankIFSC_Code { get; set; }
        public string AMST_MotherCasteCertiNo { get; set; }
        public decimal? AMST_TotalIncome { get; set; }
        public string ANST_MotherPhoto { get; set; }
        public string AMST_BirthPlace { get; set; }
        public long? AMST_Nationality { get; set; }
        public int? AMST_BPLCardFlag { get; set; }
        public string AMST_BPLCardNo { get; set; }
        public int? AMST_HostelReqdFlag { get; set; }
        public int? AMST_TransportReqdFlag { get; set; }
        public int? AMST_GymReqdFlag { get; set; }
        public int? AMST_ECSFlag { get; set; }
        public int? AMST_PaymentFlag { get; set; }
        public int? AMST_AmountPaid { get; set; }
        public string AMST_PaymentType { get; set; }
        public DateTime? AMST_PaymentDate { get; set; }
        public string AMST_ReceiptNo { get; set; }
        public int? AMST_ActiveFlag { get; set; }
        public string AMST_ApplStatus { get; set; }
        public int? AMST_FinalpaymentFlag { get; set; }
        public string AMST_Photoname { get; set; }
        public string AMST_SOL { get; set; }

        public long? AMST_Noofbrothers { get; set; }

        public long? AMST_Noofsisters { get; set; }
        public string AMST_Father_Signature { get; set; }
        public string AMST_Father_FingerPrint { get; set; }
        public string AMST_Mother_Signature { get; set; }
        public string AMST_Mother_FingerPrint { get; set; }
        public long? AMST_Concession_Type { get; set; }
        public string AMST_SubCasteIMC_Id { get; set; }
        public string AMST_FatherReligion { get; set; }
        public string AMST_FatherCaste { get; set; }
        public string AMST_FatherSubCaste { get; set; }
        public string AMST_MotherReligion { get; set; }
        public string AMST_MotherCaste { get; set; }
        public string AMST_MotherSubCaste { get; set; }
        public string AMST_Tpin { get; set; }
        public string AMST_GovtAdmno { get; set; }
        public string AMST_StudentPANNo { get; set; }
        public string AMST_FatherPANNo { get; set; }
        public string AMST_MotherPANNo { get; set; }
        public string AMST_LanguageSpoken { get; set; }
        public string AMST_GPSTrackingId { get; set; }
        public string AMST_AppDownloadedDeviceId { get; set; }
        public int? AMST_NoOfElderBrothers { get; set; }
        public int? AMST_NoOfYoungerBrothers { get; set; }
        public int? AMST_NoOfElderSisters { get; set; }
        public int? AMST_NoOfYoungerSisters { get; set; }
        public long? ASMST_Id { get; set; }
        public string AMST_SecretCode { get; set; }
        public string AMST_BiometricId { get; set; }
        public string AMST_MOInstruction { get; set; }
    }
}
